[dependencies]
zip = "*"
sevenz-rust = "*"
sha2 = "*"
eframe = "*"
egui = "*"
rfd = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
license = "MIT OR Apache-2.0"
authors = ["Uri-Yuan Kerr <uriyuankerr@outlook.com>"]

[profile.release]
strip = true  # Strip symbols from binary for smaller size
lto = true    # Link Time Optimization for better performance
