[dependencies]
zip = "0.6"
sevenz-rust = "0.1"
sha2 = "0.10"
eframe = "0.22.0"
egui = "0.22.0"
rfd = "0.11.2"  # Check for the latest version
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
