[package]
name = "SimpleModManager-Rust"
version = "0.1.0"
edition = "2021"

[dependencies]
# Use caret (^) for semantic versioning which allows auto-updates to patch releases
eframe = "^0.22.0"
egui = "^0.22.0"
rfd = "^0.11.3"
serde = { version = "^1.0.160", features = ["derive"] }
serde_json = "^1.0.96"
sevenz-rust = "^0.1.0"
sha2 = "^0.10.6"
zip = "^0.6.4"

# Profile for release builds
[profile.release]
opt-level = 'z'  # Optimize for size
lto = true       # Link Time Optimization
codegen-units = 1  # Increase compilation time but reduces binary size
strip = true     # Strip symbols from binary

[features]
default = []

# Additional features can be added here if needed
