[package]
name = "SimpleModManager-Rust"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "windows")]
build-dependencies = ["winres"]
[target.'cfg(target_os = "macos")]
build-dependencies = ["cbindgen"]

[dependencies]
eframe = { version = "0.22.*", features = ["default-assets", "winit"] }
egui = { version = "0.22.*", features = ["winit", "serde"] }
rfd = "0.11.3"
serde = { version = "1.0.*", features = ["derive", "serialize", "deserialize"] }
serde_json = "1.0.*"
sevenz-rust = { version = "0.1.0", features = ["bin_progs"] }
sha2 = "0.10.*"
zip = "0.6.*"

# Additional features can be added here if needed
