[dependencies]
zip = "0.6"
sevenz-rust = "0.1"
sha2 = "0.10"
eframe = "0.22.0"
egui = "0.22.0"
rfd = "0.11.2"  # Check for the latest version
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
license = "MIT OR Apache-2.0"
authors = ["Uri-Yuan Kerr <uriyuankerr@outlook.com>"]

[profile.release]
strip = true  # Strip symbols from binary for smaller size
lto = true    # Link Time Optimization for better performance
