[package]
name = "SimpleModManager-Rust"
version = "0.1.0"
edition = "2021"

# Additional features for Windows
[target.'cfg(target_os = "windows") && target.'cfg(target_env = "msvc") ]
build-dependencies = ["cargo-winres"]

# Additional features can be added here if needed

[dependencies]
eframe = { version = "0.22.*", features = ["default-assets", "winit"] }
egui = { version = "0.22.*", features = ["winit", "serde"] }
rfd = "0.11.3"
serde = { version = "1.0.*", features = ["derive", "serialize", "deserialize"] }
serde_json = "1.0.*"
sevenz-rust = { version = "0.1.0", features = ["bin_progs"] }
sha2 = { version = "0.10.*", features = ["std"] }
zip = { version = "0.6.*", features = ["deflate", "bzip2", "lzma"] }

# Additional dependencies can be added here if needed

[lib]
name = "simplemodmanager"
crate-type = ["cdylib", "rlib"]

# Additional configuration for the library can be added here if needed

# Cargo.toml configuration for Windows
[profile.release]
debug = false
opt-level = "z"
lto = true

[profile.release.build-override]
rustc-flags = ["-C", "link-arg=-s"]

# Additional build configuration for other targets can be added here if needed
