name: Build and Create Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_artifact:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust and Dependencies
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable  # Always use the latest stable version
          target: ${{ matrix.target }}
          override: true

      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target }}
          if [ "${{ runner.os }}" = "Windows" ]; then
            mv target/${{ matrix.target }}/release/SimpleModManager-Rust.exe SimpleModManager-Rust${{ matrix.target.extension }}
          fi
        shell: bash

      - name: Create Artifact
        if: ${{ success() && matrix.target != 'x86_64-unknown-linux-gnu' }}
        run: |
          echo "Creating artifact for ${{ matrix.target }}"
          cp target/${{ matrix.target }}/release/SimpleModManager-Rust${{ matrix.target.extension }} SimpleModManager-Rust.${{ matrix.target.extension }}
        shell: bash

      - name: Upload Artifact
        if: ${{ success() && matrix.target != 'x86_64-unknown-linux-gnu' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-binaries
          path: SimpleModManager-Rust.${{ matrix.target.extension }}
