name: Build and Create Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_artifacts:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        target: [x86_64-unknown-linux-gnu, x86_64-apple-darwin, x86_64-pc-windows-msvc]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: rust-lang/rust-action@v1
        with:
          rust-version: nightly
          toolchain: stable

      - name: Set up Cargo
        if: ${{ matrix.os == 'windows-latest' && matrix.target == 'x86_64-pc-windows-msvc' }}
        run: cargo install --version 0.63.0-nightly cargo-winres
        shell: cmd

      - name: Build for ${{ matrix.os }}, ${{ matrix.target }}
        run: cargo build --release --target ${{ matrix.target }}
        shell: bash

      - name: Create Artifact
        if: ${{ success() && matrix.os == runner.os && matrix.target == runner.arch }}
        run: echo "Creating artifact for ${{ matrix.target }}"
        shell: bash

      - name: Upload Artifact
        if: ${{ success() && matrix.os == runner.os && matrix.target == runner.arch }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-binaries
          path: target/release/SimpleModManager-Rust
