name: Build and Create Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_artifact:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust and Dependencies
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.os }}-${{ matrix.target }}
          override: true

      - name: Build
        run: |
          cargo build --release --target ${{ matrix.os }}-${{ matrix.target }}
        shell: bash

      - name: Create Artifact
        if: ${{ success() && matrix.os != 'macos-latest' }}
        run: |
          echo "Creating artifact for ${{ matrix.target }}"
          cp target/${{ matrix.os }}-${{ matrix.target }}/release/SimpleModManager-Rust${{ matrix.target.extension }} SimpleModManager-Rust.${{ matrix.target.extension }}
        shell: bash

      - name: Upload Artifact
        if: ${{ success() && matrix.os != 'macos-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-binaries
          path: SimpleModManager-Rust.${{ matrix.target.extension }}
