name: Build and Create Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_artifacts:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12, windows-latest]
        rust-version: [nightly]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-version }}
        override: true

    - name: Set up Cargo (Windows)
      if: runner.os == 'Windows'
      run: |
        cargo install --version ${{ matrix.rust-version }}.y cargo-winres
      shell: bash

    - name: Build
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          cargo build --release --target x86_64-pc-windows-msvc
        elif [[ "$RUNNER_OS" == "Linux" ]]; then
          cargo build --release --target x86_64-unknown-linux-gnu
        else
          cargo build --release --target x86_64-apple-darwin
        fi
      shell: bash

    - name: Create Artifact
      run: echo "Creating artifact for ${{ matrix.os }}"
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-binaries
        path: |
          target/release/SimpleModManager-Rust*
